---
name: RPM

on:
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo Success

  repoclosure:
    name: Repoclosure
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Repoclosure
        run: echo All good
